name: Humble

on:
  push:
  pull_request:
  schedule:
    # Run every Friday at 6:30 am to detect breaking APIs
    - cron: '30 6 * * 5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  industrial_ci:
    env:
      BEFORE_BUILD_TARGET_WORKSPACE: '.github/script/install_dependencies.sh'
      BEFORE_RUN_TARGET_TEST: '.github/script/install_dummy.sh'

    strategy:
      fail-fast: false
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
